---
- name: Install Kubernetes toolchain to worker nodes
  hosts: workers
  become: True
  tasks:
      - name: Install Kubernetes toolchain
        ansible.builtin.apt:
            update_cache: True
            name:
                - kubeadm
                - kubelet
            state: present
      - name: Copy join script
        copy:
            src: ../../scripts/worker-join.sh
            dest: /worker-join.sh
      - name: Join to the cluster
        shell: bash /worker-join.sh
